project_name: mchurl
before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
  - id: mchurl_darwin
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: mchurl_linux
    main: ./main.go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - 386
archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - config.example.yaml
    - README.md
    - ui/public/*
    - ui/build/*
    - ui/build/**/*
    - ui/build/static/css/*
    - ui/build/static/js/*
    - templates/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github: